In [4]:
#add direction by path
import os
os.chdir('C:\\Users\\rakib\\OneDrive\\Desktop\\MachineLearning\\IrisFlower')

In [5]:
os.getcwd()

'C:\\Users\\rakib\\OneDrive\\Desktop\\MachineLearning\\IrisFlower'

In [6]:
#import library
import pandas as pd
import numpy as np

In [7]:
#make dataset or read data set by pandas
dataset=pd.read_csv('Iris.csv')

In [8]:
dataset.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [9]:
#split features to x
x=dataset.iloc[:, 1: 5].values

In [10]:
#split target value to y
y=dataset.iloc[: , 5: ].values


In [11]:
# Encode y from string class to numberclass
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)

C:\Users\rakib\anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
#split test and train data by sklearn 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2)

# using LogisticRegression Algorithm from linear model

In [14]:
#using LogisticRegression Algorithm from linear model
from sklearn.linear_model import LogisticRegression
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)
y_pred=logmodel.predict(x_test)

C:\Users\rakib\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [15]:
#making confusion matrix for data validation
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  9]], dtype=int64)

In [16]:
29/30


0.9666666666666667

In [17]:
#predict 96% by LogisticRegression on Linear Model

# Using KNeighborsClassifier Algorithm of neighbors Model

In [18]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn=KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)
classifier_knn.fit(x_train,y_train)


KNeighborsClassifier()

In [19]:
y_pred=classifier_knn.predict(x_test)

In [20]:
y_pred

array([0, 1, 2, 2, 1, 2, 0, 2, 0, 0, 0, 2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 0,
       2, 0, 1, 2, 0, 1, 1, 1])

In [21]:
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  9]], dtype=int64)

In [22]:
28/30


0.9333333333333333

In [23]:
#predict 93% by KNeighborsClassifier Algorithm of neighbors model

# Using GussianNB algorithm of naive_bayes 

In [24]:
from sklearn.naive_bayes import GaussianNB
classifier_nb=GaussianNB()
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [26]:
y_pred=classifier_nb.predict(x_test)

In [27]:
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 11,  2],
       [ 0,  0,  9]], dtype=int64)

In [28]:
28/30


0.9333333333333333

In [29]:
#predict 93% by Gaussian Algorithm of nave_bayes Model

# Using suppport vector machine algorithm

In [37]:
from sklearn.svm import SVC
classifier_svm_sigmoid=SVC(kernel='sigmoid')
classifier_svm_sigmoid.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [40]:
y_pred=classifier_svm_sigmoid.predict(x_test)

In [41]:
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [13,  0,  0],
       [ 9,  0,  0]], dtype=int64)

In [42]:
8/30

0.26666666666666666

In [44]:
#predict 26% by Suppport vector machine Algorithm sigmoid kernel

In [45]:
from sklearn.svm import SVC
classifier_svm_sigmoid=SVC(kernel='linear')
classifier_svm_sigmoid.fit(x_train,y_train)

SVC(kernel='linear')

In [46]:
y_pred=classifier_svm_sigmoid.predict(x_test)

In [47]:
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  9]], dtype=int64)

In [48]:
30/30

1.0

In [49]:
#predict 100% by Suppport vector machine Algorithm linear kernel

# Using DecisionTreeClassifier Algorithm

In [56]:
from sklearn.tree import DecisionTreeClassifier
classifier_dt=DecisionTreeClassifier()
classifier_dt.fit(x_train,y_train);


In [57]:
y_pred=classifier_dt.predict(x_test)

In [58]:
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  1],
       [ 0,  1,  8]], dtype=int64)

In [59]:
28/30

0.9333333333333333

In [55]:
#predict 93% by DecissionTreeClassifier algo of Tree model

# using RandomForest algo of Ensamble model

In [63]:
from sklearn.ensemble import RandomForestClassifier
classifier_rdf=RandomForestClassifier()
classifier_rdf.fit(x_train,y_train)

RandomForestClassifier()

In [65]:
y_pred=classifier_rdf.predict(x_test)

In [68]:
confusion_matrix(y_test,y_pred)

array([[ 8,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  9]], dtype=int64)

In [69]:
29/30


0.9666666666666667

In [70]:
#96%